# Generated by Django 4.1.3 on 2022-11-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_cat_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(choices=[('Забота о себе', 'Self Care'), ('Зарплата', 'Salary'), ('Здоровье и фитнес', 'Health And Fitness'), ('Кафе и рестораны', 'Cafes And Restaurants'), ('Машина', 'Car'), ('Образование', 'Education'), ('Отдых и развлечения', 'Recreation And Entertainment'), ('Платежи, комиссии', 'Payments Commissions'), ('Покупки: одежда, техника', 'Shopping Clothes Appliances'), ('Продукты', 'Products'), ('Проезд', 'Directions')], default='Забота о себе', max_length=50),
        ),
    ]
