# Generated by Django 4.1.3 on 2022-11-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], max_length=50, verbose_name='Вид'),
        ),
    ]
